import type { Metadata } from "next";
import { Rubik } from "next/font/google";

import "../styles";

const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
